from InfrastructureSVG.Projects.FiveG.CoreCare.CoreCareData import DEFECT_OPEN_STATUS_LIST_JIRA_SYNTAX, DEFECT_CLOSE_STATUS_LIST_JIRA_SYNTAX


VERSIONS_PATH = {
    'cu_path': '\\\\192.168.127.231\\SWImages\\CU',
    'du_path': '\\\\192.168.127.231\\SWImages\\DU',
    'ru_path': '\\\\192.168.127.231\\SWImages\\RU',
    'defects_path': '\\\\192.168.127.231\\defects',
}

DEFECT_OPEN_STATUS_LIST_JIRA_SYNTAX = DEFECT_OPEN_STATUS_LIST_JIRA_SYNTAX

DEFECT_CLOSE_STATUS_LIST_JIRA_SYNTAX = DEFECT_CLOSE_STATUS_LIST_JIRA_SYNTAX
